const { DirectSecp256k1HdWallet, Registry } = require("@cosmjs/proto-signing");
const { SigningStargateClient, GasPrice } = require("@cosmjs/stargate");
const { MsgExecuteContract } = require("cosmjs-types/cosmwasm/wasm/v1/tx");
const { toUtf8 } = require("@cosmjs/encoding");
const { Slip10RawIndex } = require("@cosmjs/crypto");
const { ethers, JsonRpcProvider, Wallet } = require("ethers");
const axios = require("axios");
const moment = require("moment-timezone");
const fs = require("fs").promises;
const path = require("path");
const prompt = require("prompt-sync")();
const crypto = require("crypto");
const chalk = require("chalk");
const TelegramBot = require("node-telegram-bot-api");
require("dotenv").config();
